In [1]:
import pandas as pd
import numpy as np

In [2]:
class_roster = pd.read_csv("Classes_With_Medians.csv")
rmp_data = pd.read_csv("RMP/RMP.csv")
medians= pd.read_csv("Cornell_Median_Grades.csv")

In [3]:
semesterdict = {"FA21":0, 'SP21':1, 'FA20':2, 'SP20':3, 'FA19':4,'SP19':5,'FA18':6,'SP18':7,'FA17':8,'SP17':9,'FA16':10}

In [4]:
#Data cleaning for medians
medians['Semester'] = medians['Semester (Ex: SP21)']
medians = medians.replace({"Semester": semesterdict})
medians = medians.sort_values(by="Semester")
medians = medians.drop_duplicates(subset="Dept + Number", keep="first")
medians.to_csv("Cleaned_Medians.csv")

In [5]:
courses = []
for row in class_roster.to_numpy():
    course = row[1]+" " + str(row[2])
    courses.append(course)

In [6]:
pre_coreqs = []
for row in class_roster.to_numpy():
    preco = row[-7] #normally negative 6, if running again then -7
    new_list = []
    #print(type(preco))
    if type(preco) == str or not (np.isnan(preco)):
        
        for course in courses:
            if course in preco:
                new_list.append(course)
    else:
        new_list.append(np.nan)
    pre_coreqs.append(new_list)
#pre_coreqs
class_roster["Pre/Coreqs"] = pre_coreqs

In [7]:
full_data = class_roster.merge(rmp_data, left_on='Professor', right_on ="Name", how="outer")

In [8]:
full_data

,Unnamed: 0,Dept,Number,Course_Name,Professor,Start_Time,End_Time,Location,Description,Pre/coreqs,...,Median Grade,Semester (Ex: SP21),Semester,Pre/Coreqs,ID,Name,Number_of_Ratings,Average_Rating,Difficulty,Take Again
0,0.0,CS,1110.0,Introduction to Computing Using Python,Anne Bracy,09:05AM,09:55AM,Bailey Hall 101,Programming and problem solving using Python. ...,NaN,...,B+,FA21,0.0,[],2109847.0,Anne Bracy,43.0,3.0,4.0,52.5
1,16.0,CS,3410.0,Computer System Organization and Programming,Anne Bracy,11:20AM,12:10PM,Uris Hall G01,"Introduction to computer organization, systems...",Prerequisite: CS 2110Â or equivalent programmin...,...,B+,FA21,0.0,[],2109847.0,Anne Bracy,43.0,3.0,4.0,52.5
2,1.0,CS,1112.0,Introduction to Computing Using MATLAB,Kit-Yee Daisy Fan,02:40PM,03:30PM,Hollister Hall B14,Programming and problem solving using MATLAB. ...,"Corequisite: MATH 1110, MATH 1910, or equivalent.",...,B,FA21,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,CS,1132.0,Short Course in MATLAB,Kit-Yee Daisy Fan,02:40PM,03:30PM,Phillips Hall 219,Introduction to the MATLAB programming languag...,NaN,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,CS,1133.0,Short Course in Python,Craig Frey,12:25PM,01:15PM,Upson Hall 142,Introduction to the Python programming languag...,NaN,...,NaN,NaN,NaN,[],2555662.0,Craig Frey,2.0,4.5,1.5,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1403262.0,Thomas Zittel,1.0,3.0,2.0,-1.0
2984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2384073.0,Sasa Zivkovic,2.0,2.5,4.5,50.0
2985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,951234.0,Jeffrey Zorn,6.0,4.5,3.2,100.0
2986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2090822.0,Brad Zukovic,1.0,4.0,1.0,100.0
2987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2171095.0,David Zywina,11.0,4.6,2.9,100.0

In [9]:
full_data.columns

Index(['Unnamed: 0', 'Dept', 'Number', 'Course_Name', 'Professor',
       'Start_Time', 'End_Time', 'Location', 'Description', 'Pre/coreqs',
       'Offered', 'Dept + Number', 'Median Grade', 'Semester (Ex: SP21)',
       'Semester', 'Pre/Coreqs', 'ID', 'Name', 'Number_of_Ratings',
       'Average_Rating', 'Difficulty', 'Take Again'],
      dtype='object')

In [10]:
full_data['Semester'] = full_data['Semester (Ex: SP21)']
full_data = full_data.replace({"Semester": semesterdict})
full_data = full_data.sort_values(by="Semester")
full_data = full_data.drop_duplicates(subset="Dept + Number", keep="first")
full_data = full_data.drop_duplicates(subset="Course_Name", keep="first")

In [11]:
full_data=full_data.drop(columns=["Unnamed: 0"])

In [12]:
full_data.drop

,Dept,Number,Course_Name,Professor,Start_Time,End_Time,Location,Description,Pre/coreqs,Offered,...,Median Grade,Semester (Ex: SP21),Semester,Pre/Coreqs,ID,Name,Number_of_Ratings,Average_Rating,Difficulty,Take Again
0,CS,1110.0,Introduction to Computing Using Python,Anne Bracy,09:05AM,09:55AM,Bailey Hall 101,Programming and problem solving using Python. ...,NaN,"Fall, Spring, Summer.",...,B+,FA21,0.0,[],2109847.0,Anne Bracy,43.0,3.0,4.0,52.5000
129,INFO,3450.0,Human-Computer Interaction Design,Qian Yang,01:30PM,02:20PM,Hollister Hall B14,This course focuses on user experience design ...,NaN,"Fall, Spring, Summer.",...,A,FA21,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN
152,INFO,4940.0,Special Topics in Information Science,Sharlane Cleare,01:00PM,02:15PM,Frank H T Rhodes Hall 253,Study of topics not currently covered in INFO ...,NaN,"Fall, Spring.",...,A+,FA21,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN
169,ECE,2100.0,Introduction to Circuits for Electrical and Co...,Carl Poitras,10:10AM,11:00AM,Phillips Hall 219,This course is an introduction to electronic c...,Prerequisite: MATH 1920Â or PHYS 1112. Corequis...,"Fall, Spring.",...,A-,FA21,0.0,[],1825700.0,Carl Poitras,36.0,4.1,3.3,87.8788
508,AEM,3205.0,Ethics in Business and Organizations,John Doris,09:40AM,10:55AM,Malott Hall 251,This course will survey ethical problems that ...,Prerequisite: AEM 2200Â or equivalent.,"Fall, Spring.",...,A,FA21,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,BME,6260.0,Optical Microscopy and Fluorescence Methods fo...,Warren Zipfel,01:30PM,02:20PM,Weill Hall 224,"BME 6260 covers the fundamental optics, photop...","Prerequisite: physics, biology and calculus.Â Y...",Spring.,...,NaN,NaN,NaN,[BME 6260],NaN,NaN,NaN,NaN,NaN,NaN
915,BME,6410.0,Cell and Molecular Mechanobiology,Jan Lammerding,09:40AM,10:55AM,Weill Hall 224,Mechanobiology describes how cells and tissues...,"Prerequisite: BIOMG 1350Â or equivalent, BME 30...",Spring.,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN
916,BME,7030.0,Graduate Student Teaching Experience,Jan Lammerding,NaN,NaN,To Be Assigned,Guided individual experience in laboratory ins...,NaN,"Fall, Spring.",...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN
917,BME,7130.0,Core Concepts in Disease,Nate Cira,11:25AM,12:40PM,Weill Hall 226,Most diseases emerge due to a relative small n...,Prerequisite: introductory biology.,Spring.,...,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN
918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2510713.0,Mustafa Abadan,0.0,0.0,0.0,-1.0000

In [156]:
full_data.to_csv("Full_Data.csv")