In [1]:
import pandas as pd
import numpy as np

In [2]:
class_roster = pd.read_csv("Classes_With_Medians_FA22.csv")
rmp_data = pd.read_csv("RMP/RMP.csv")
medians= pd.read_csv("Cornell_Median_Grades_v2.csv")

In [3]:
semesterdict = {"FA21":0, 'SP21':1, 'FA20':2, 'SP20':3, 'FA19':4,'SP19':5,'FA18':6,'SP18':7,'FA17':8,'SP17':9,'FA16':10}

In [4]:
#Data cleaning for medians
medians['Semester'] = medians['Semester (Ex: SP21)']
medians = medians.replace({"Semester": semesterdict})
medians = medians.sort_values(by="Semester")
medians = medians.drop_duplicates(subset="Dept + Number", keep="first")
#medians.to_csv("Cleaned_Medians.csv")

In [5]:
class_roster=class_roster.drop(columns="Unnamed: 0")

In [6]:
class_roster

,Dept,Number,Course_Name,Professor_x,Start_Time,End_Time,Location,Description,Pre/coreqs,Offered,Dept + Number,Unnamed: 0.1,Professor_y,Median Grade,Semester (Ex: SP21),# of Students,Notes,Semester
0,AAS,2100,South Asian Diaspora,Viranjini Munasinghe,02:55PM,04:10PM,To Be Assigned,This interdisciplinary course (with an emphasi...,NaN,Fall.,AAS 2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAS,2130,Introduction to Asian American History,Derek Chang,11:25AM,12:40PM,To Be Assigned,"An introductory history of Chinese, Japanese, ...",NaN,Fall.,AAS 2130,1.0,Chang,A,FA21,52.0,"crosslisted with AMST 2640, HIST 2640",0.0
2,AAS,3885,"Race and War in History: Workers, Soldiers, Pr...",Tejasvi Nagaraja,01:00PM,02:15PM,To Be Assigned,"Across twentieth-century history, race and war...",NaN,NaN,AAS 3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAS,4040,Fictions of Dictatorship,Christine Balance,02:40PM,05:10PM,To Be Assigned,"Fictions of dictatorship, as termed by scholar...",NaN,Fall.,AAS 4040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAS,4950,Independent Study,Viranjini Munasinghe,NaN,NaN,NaN,Independent reading course in topics not cover...,NaN,"Fall, Spring.",AAS 4950,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4157,YORUB,2110,Intermediate Yoruba I,Adeolu Ademoyo,09:05AM,09:55AM,To Be Assigned,The intermediate course extends the developmen...,Prerequisite: YORUB 1109.,Fall.,YORUB 2110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4158,YORUB,3110,Advanced Yoruba I,Adeolu Ademoyo,07:30PM,09:25PM,To Be Assigned,This course will help students expand their un...,Prerequisite: YORUB 2111.,Fall.,YORUB 3110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4159,ZULU,1113,Elementary Zulu I,Angelika Kraemer,11:35AM,12:25PM,To Be Assigned,"A beginning course in conversational isiZulu, ...",NaN,Fall.,ZULU 1113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4160,ZULU,2116,Intermediate Zulu I,Angelika Kraemer,09:25AM,10:15AM,To Be Assigned,"Development of fluency in speaking, listening,...",NaN,Fall.,ZULU 2116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4161,ZULU,3113,Advanced Zulu I,Angelika Kraemer,04:00PM,05:15PM,To Be Assigned,"Development of fluency in using idioms, speaki...",NaN,Fall.,ZULU 3113,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
class_roster[class_roster['Course_Name']=='Problems in Byzantine Art']

Empty DataFrame
Columns: [Dept, Number, Course_Name, Professor_x, Start_Time, End_Time, Location, Description, Pre/coreqs, Offered, Dept + Number, Unnamed: 0.1, Professor_y, Median Grade, Semester (Ex: SP21), # of Students, Notes, Semester]
Index: []

In [8]:
courses = []
for row in class_roster.to_numpy():
    course = row[0]+" " + str(row[1])
    courses.append(course)

In [9]:
pre_coreqs = []
for row in class_roster.to_numpy():
    preco = row[-6] #normally  -6, if running again then -7
    new_list = []
    #print(type(preco))
    if type(preco) == str or not (np.isnan(preco)):
        
        for course in courses:
            if course in preco:
                new_list.append(course)
    else:
        new_list.append(np.nan)
    pre_coreqs.append(new_list)
#pre_coreqs
class_roster["Pre/Coreqs_Clean"] = pre_coreqs

In [12]:
class_roster

,Dept,Number,Course_Name,Professor_x,Start_Time,End_Time,Location,Description,Pre/coreqs,Offered,Dept + Number,Unnamed: 0.1,Professor_y,Median Grade,Semester (Ex: SP21),# of Students,Notes,Semester,Pre/Coreqs_Clean
0,AAS,2100,South Asian Diaspora,Viranjini Munasinghe,02:55PM,04:10PM,To Be Assigned,This interdisciplinary course (with an emphasi...,NaN,Fall.,AAS 2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
1,AAS,2130,Introduction to Asian American History,Derek Chang,11:25AM,12:40PM,To Be Assigned,"An introductory history of Chinese, Japanese, ...",NaN,Fall.,AAS 2130,1.0,Chang,A,FA21,52.0,"crosslisted with AMST 2640, HIST 2640",0.0,[]
2,AAS,3885,"Race and War in History: Workers, Soldiers, Pr...",Tejasvi Nagaraja,01:00PM,02:15PM,To Be Assigned,"Across twentieth-century history, race and war...",NaN,NaN,AAS 3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
3,AAS,4040,Fictions of Dictatorship,Christine Balance,02:40PM,05:10PM,To Be Assigned,"Fictions of dictatorship, as termed by scholar...",NaN,Fall.,AAS 4040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
4,AAS,4950,Independent Study,Viranjini Munasinghe,NaN,NaN,NaN,Independent reading course in topics not cover...,NaN,"Fall, Spring.",AAS 4950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4157,YORUB,2110,Intermediate Yoruba I,Adeolu Ademoyo,09:05AM,09:55AM,To Be Assigned,The intermediate course extends the developmen...,Prerequisite: YORUB 1109.,Fall.,YORUB 2110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
4158,YORUB,3110,Advanced Yoruba I,Adeolu Ademoyo,07:30PM,09:25PM,To Be Assigned,This course will help students expand their un...,Prerequisite: YORUB 2111.,Fall.,YORUB 3110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
4159,ZULU,1113,Elementary Zulu I,Angelika Kraemer,11:35AM,12:25PM,To Be Assigned,"A beginning course in conversational isiZulu, ...",NaN,Fall.,ZULU 1113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
4160,ZULU,2116,Intermediate Zulu I,Angelika Kraemer,09:25AM,10:15AM,To Be Assigned,"Development of fluency in speaking, listening,...",NaN,Fall.,ZULU 2116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
4161,ZULU,3113,Advanced Zulu I,Angelika Kraemer,04:00PM,05:15PM,To Be Assigned,"Development of fluency in using idioms, speaki...",NaN,Fall.,ZULU 3113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]

In [13]:
full_data = class_roster.merge(rmp_data, left_on='Professor_x', right_on ="Name", how="outer")

In [14]:
full_data.shape

(5876, 25)

In [15]:
full_data['Semester'] = full_data['Semester (Ex: SP21)']
full_data = full_data.replace({"Semester": semesterdict})
full_data = full_data.sort_values(by="Semester")
full_data = full_data.drop_duplicates(subset="Dept + Number", keep="first")
print(full_data.shape)
#full_data = full_data.drop_duplicates(subset="Course_Name", keep="first")

(4163, 25)

In [16]:
full_data.shape

(4163, 25)

In [14]:
#full_data=full_data.drop(columns=["Unnamed: 0"])

In [17]:
full_data

,Dept,Number,Course_Name,Professor_x,Start_Time,End_Time,Location,Description,Pre/coreqs,Offered,...,# of Students,Notes,Semester,Pre/Coreqs_Clean,ID,Name,Number_of_Ratings,Average_Rating,Difficulty,Take Again
5,AAS,2130.0,Introduction to Asian American History,Derek Chang,11:25AM,12:40PM,To Be Assigned,"An introductory history of Chinese, Japanese, ...",NaN,Fall.,...,52.0,"crosslisted with AMST 2640, HIST 2640",0.0,[],333013.0,Derek Chang,25.0,4.0,2.0,78.5714
2131,CS,4701.0,Practicum in Artificial Intelligence,Bart Selman,NaN,NaN,NaN,Artificial Intelligence project class. Possibl...,"Prerequisite: CS 4670, CS 4700, CS 4740, or CS...","Fall, Spring.",...,125.0,NaN,0.0,[],154695.0,Bart Selman,17.0,2.1,2.5,0.0000
2140,CS,4780.0,Introduction to Machine Learning,Anil Damle,09:40AM,10:55AM,To Be Assigned,The course provides an introduction to machine...,Prerequisite: probability theory (e.g. BTRY 30...,"Fall, Spring.",...,309.0,NaN,0.0,[],2473568.0,Anil Damle,4.0,5.0,3.5,100.0000
2244,DEA,4500.0,Policy Meets Design: High-Impact Facilities of...,Rana Zadeh,02:45PM,04:00PM,To Be Assigned,Active participation from local and global lea...,NaN,Fall.,...,16.0,NaN,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN
2268,EAS,1600.0,Environmental Physics,Susan Riha,NaN,NaN,To Be Assigned,"Fundamentals of radiation, thermodynamics, and...",Prerequisite: mathematics through high school ...,"Fall, Spring.",...,35.0,NaN,0.0,[],2432925.0,Susan Riha,0.0,0.0,0.0,-1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4158,WRIT,7101.0,Writing in the Majors Seminar,Elliot Shapiro,07:00PM,09:15PM,To Be Assigned,Teaching assistants assigned to Writing in the...,NaN,"Fall, Spring.",...,NaN,NaN,NaN,[nan],NaN,NaN,NaN,NaN,NaN,NaN
4159,YORUB,1108.0,Introduction to Yoruba I,Adeolu Ademoyo,10:10AM,11:00AM,To Be Assigned,A two-semester beginner's course in Yoruba Lan...,NaN,Fall.,...,NaN,NaN,NaN,[nan],1515016.0,Adeolu Ademoyo,5.0,4.1,1.2,-1.0000
4160,YORUB,2110.0,Intermediate Yoruba I,Adeolu Ademoyo,09:05AM,09:55AM,To Be Assigned,The intermediate course extends the developmen...,Prerequisite: YORUB 1109.,Fall.,...,NaN,NaN,NaN,[nan],1515016.0,Adeolu Ademoyo,5.0,4.1,1.2,-1.0000
4161,YORUB,3110.0,Advanced Yoruba I,Adeolu Ademoyo,07:30PM,09:25PM,To Be Assigned,This course will help students expand their un...,Prerequisite: YORUB 2111.,Fall.,...,NaN,NaN,NaN,[nan],1515016.0,Adeolu Ademoyo,5.0,4.1,1.2,-1.0000
4162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2510713.0,Mustafa Abadan,0.0,0.0,0.0,-1.0000

In [18]:
full_data.to_csv("Full_Data_FA22.csv")