In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('FullerData_CUReviews_FA22.csv')

In [10]:
data.head()

,Unnamed: 0,Dept,Number,Course_Name,Professor_x,Start_Time,End_Time,Location,Description,Pre/coreqs,...,Pre/Coreqs_Clean,ID,Name,Number_of_Ratings,Average_Rating,Difficulty,Take Again,CU_Reviews_Difficulty,CU_Reviews_Rating,CU_Reviews_Workload
0,0,AAS,2130,Introduction to Asian American History,Derek Chang,11:25AM,12:40PM,To Be Assigned,"An introductory history of Chinese, Japanese, ...",NaN,...,[],333013.0,Derek Chang,25.0,4.0,2.0,78.5714,1.67,4.00,2.33
1,1,CS,4701,Practicum in Artificial Intelligence,Bart Selman,NaN,NaN,NaN,Artificial Intelligence project class. Possibl...,"Prerequisite: CS 4670, CS 4700, CS 4740, or CS...",...,[],154695.0,Bart Selman,17.0,2.1,2.5,0.0000,1.00,2.67,1.00
2,2,CS,4780,Introduction to Machine Learning,Anil Damle,09:40AM,10:55AM,To Be Assigned,The course provides an introduction to machine...,Prerequisite: probability theory (e.g. BTRY 30...,...,[],2473568.0,Anil Damle,4.0,5.0,3.5,100.0000,3.43,4.00,3.26
3,3,DEA,4500,Policy Meets Design: High-Impact Facilities of...,Rana Zadeh,02:45PM,04:00PM,To Be Assigned,Active participation from local and global lea...,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,EAS,1600,Environmental Physics,Susan Riha,NaN,NaN,To Be Assigned,"Fundamentals of radiation, thermodynamics, and...",Prerequisite: mathematics through high school ...,...,[],2432925.0,Susan Riha,0.0,0.0,0.0,-1.0000,3.67,2.60,3.40

In [19]:
data[data['Pre/coreqs'].str.contains('CS')==True]

,Unnamed: 0,Dept,Number,Course_Name,Professor_x,Start_Time,End_Time,Location,Description,Pre/coreqs,...,Pre/Coreqs_Clean,ID,Name,Number_of_Ratings,Average_Rating,Difficulty,Take Again,CU_Reviews_Difficulty,CU_Reviews_Rating,CU_Reviews_Workload
1,1,CS,4701,Practicum in Artificial Intelligence,Bart Selman,NaN,NaN,NaN,Artificial Intelligence project class. Possibl...,"Prerequisite: CS 4670, CS 4700, CS 4740, or CS...",...,[],154695.0,Bart Selman,17.0,2.1,2.5,0.0000,1.00,2.67,1.00
2,2,CS,4780,Introduction to Machine Learning,Anil Damle,09:40AM,10:55AM,To Be Assigned,The course provides an introduction to machine...,Prerequisite: probability theory (e.g. BTRY 30...,...,[],2473568.0,Anil Damle,4.0,5.0,3.5,100.0000,3.43,4.00,3.26
8,8,ECE,2300,Digital Logic and Computer Organization,David Albonesi,11:25AM,12:40PM,To Be Assigned,This course provides an introduction to the de...,Prerequisite: CS 1110 or CS 1112.,...,[],1582680.0,David Albonesi,21.0,4.1,3.0,85.7143,3.14,3.64,3.36
9,9,ECE,2400,Computer Systems Programming,Christopher Batten,10:10AM,11:00AM,To Be Assigned,Computer systems programming involves developi...,Prerequisite: CS 1110 (preferred) or CS 1112.,...,[],1908365.0,Christopher Batten,13.0,5.0,3.4,100.0000,3.60,4.50,4.50
10,10,ECE,2720,Data Science for Engineers,Vikram Krishnamurthy,02:45PM,04:00PM,To Be Assigned,An introduction to data science for engineers....,Prerequisite: MATH 1920 and either CS 1110 or ...,...,[],2410214.0,Vikram Krishnamurthy,5.0,4.2,3.8,80.0000,4.00,4.00,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3920,3920,PLHRT,3500,Principles of Vegetable Production,Steve Reiners,11:20AM,12:10PM,To Be Assigned,Commercial vegetable production from variety s...,"Prerequisite: PLSCI 1101, PLSCS 2600, or equiv...",...,[nan],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3943,3943,PLSCI,5190,"Cannabis: Biology, Society and Industry",Carlyn Buckler,02:45PM,04:00PM,To Be Assigned,The medical marijuana industry in the US is es...,Prerequisite: at least one college-level biolo...,...,[nan],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3953,3953,PLSCS,3630,"Soil Genesis, Classification, and Survey",Jonathan Russell-Anelli,11:20AM,12:10PM,To Be Assigned,Discusses factors and processes of soil format...,Prerequisite: PLSCS 2600.,...,[nan],646668.0,Jonathan Russell-Anelli,6.0,4.0,3.0,0.0000,NaN,NaN,NaN
3958,3958,PLSCS,3210,Soil and Crop Management for Sustainability,Harold Van Es,10:10AM,11:00AM,To Be Assigned,Students learn about agronomy and recent advan...,Prerequisite: PLSCS 1900 or PLSCS 2600.,...,[nan],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4046,4046,STSCI,5740,Data Mining and Machine Learning,Yang Ning,11:25AM,12:40PM,To Be Assigned,We start off with a detailed refresher for Lin...,"Prerequisite: CS 1112 or equivalent, MATH 2220...",...,[nan],2201480.0,Yang Ning,11.0,4.9,3.1,100.0000,NaN,NaN,NaN

In [13]:
data[data['Pre/coreqs'].str.contains('CS')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values